#!/bin/sh
# --------------------------------------------------------------
# Copyright (c) 2012 Sierra Wireless. All Rights Reserved.
# --------------------------------------------------------------
# restart_swi_apps: Simple script to restart swi apps if they are not running

# Save the HW type 
TYPE=`bsinfo -st`
DELAY=15

#  /usr/bin/swiapp > /dev/null 2>&1 &
# Bail out if this script is already running
if [ $(ps | grep restart_swiapp | wc -l) -gt 3 ]; then
  return 0
fi

while [ 1 ]
do
  sleep ${DELAY}
  # This will start swiapp if it is not running
  if [ $(ps | grep -v grep | grep "usr/bin/swiapp" | wc -l) -eq 0 ]; then
     
    # Terminate all hostapd instances - swiapp spawns them again
    killall -q hostapd
    sleep 1;
    
    # spawn swiapp
    /usr/bin/swiapp > /dev/null 2>&1 &
    
    if [ t${TYPE} = 't09' -o t${TYPE} = 't0A' -o t${TYPE} = 't0B' -o t${TYPE} = 't1C' -o t${TYPE} = 't1D' -o t${TYPE} = 't1E' -o \
           t${TYPE} = 't04' -o t${TYPE} = 't05' -o t${TYPE} = 't06' -o t${TYPE} = 't24' -o t${TYPE} = 't25' -o t${TYPE} = 't26' -o \
           t${TYPE} = 't2B' -o t${TYPE} = 't2C' ]; then
       # Stop and restart M2M specific apps to sync up
       # applicable to WP7100, WP7102, WP7104, WP7100_LARGER_MEM, WP7102_LARGER_MEM, WP7104_LARGER_MEM,
       # AR7550, AR7552, AR7554, AR7550M, AR7552M, AR7554M, AR7558M,AR7556
       /etc/init.d/startm2m.sh stop
       /etc/init.d/startm2m.sh start
    fi
  else
    if [ t${TYPE} = 't09' -o t${TYPE} = 't0A' -o t${TYPE} = 't0B' -o t${TYPE} = 't1C' -o t${TYPE} = 't1D' -o t${TYPE} = 't1E' -o \
           t${TYPE} = 't04' -o t${TYPE} = 't05' -o t${TYPE} = 't06' -o t${TYPE} = 't24' -o t${TYPE} = 't25' -o t${TYPE} = 't26' -o \
           t${TYPE} = 't2B' -o t${TYPE} = 't2C' ]; then
      # Monitor if M2M specific apps still alive
      # applicable to WP7100, WP7102, WP7104, WP7100_LARGER_MEM, WP7102_LARGER_MEM, WP7104_LARGER_MEM,
      # AR7550, AR7552, AR7554, AR7550M, AR7552M, AR7554M, AR7558M,AR7556
       /etc/init.d/startm2m.sh monitor
    fi
  fi
  DELAY=5
done
